[package]
name = "nl-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
safety-net = { version = "0.1.6", features = ["graph"] }
sv-parser = { version = "0.13.3" }
flussab-aiger = { version = "0.1.1" }
serde = { version = "1.0.219", optional = true, features = ["derive"] }
serde_json = { version = "1.0.141", optional = true }

# These are only needed to drive the example. Remove later
clap = { version = "4.5.31", features = ["derive"] }
petgraph = { version = "0.8.2" }


[features]
default = [ "serde" ]
serde = [ "dep:serde", "serde_json", "safety-net/serde" ]
